(Thu Dec  5 15:27:10 2019)(-0.124526 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
Could not find plugin library "/home/zac/anaconda3/envs/Python35/lib/python3.5/site-packages/pyscannerbit/ScannerBit/lib/libscanner_diver_1.0.0.so".

Raised at: line 102 in function Gambit::Scanner::Plugins::Plugin_Loader::Plugin_Loader() of /tmp/pip-install-01c3wqsb/pyscannerbit/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Thu Dec  5 15:27:10 2019)(-0.124497 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
Could not find plugin library "/home/zac/anaconda3/envs/Python35/lib/python3.5/site-packages/pyscannerbit/ScannerBit/lib/libscanner_diver_1.0.2.so".

Raised at: line 102 in function Gambit::Scanner::Plugins::Plugin_Loader::Plugin_Loader() of /tmp/pip-install-01c3wqsb/pyscannerbit/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Thu Dec  5 15:27:10 2019)(-0.113139 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
Could not find plugin library "/home/zac/anaconda3/envs/Python35/lib/python3.5/site-packages/pyscannerbit/ScannerBit/lib/libscanner_great.so".

Raised at: line 102 in function Gambit::Scanner::Plugins::Plugin_Loader::Plugin_Loader() of /tmp/pip-install-01c3wqsb/pyscannerbit/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Thu Dec  5 15:27:10 2019)(-0.0993886 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
Could not find plugin library "/home/zac/anaconda3/envs/Python35/lib/python3.5/site-packages/pyscannerbit/ScannerBit/lib/libscanner_multinest_3.10.so".

Raised at: line 102 in function Gambit::Scanner::Plugins::Plugin_Loader::Plugin_Loader() of /tmp/pip-install-01c3wqsb/pyscannerbit/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Thu Dec  5 15:27:10 2019)(0.0155344 [s])[Default,Utilities]:
Random number engine mt19937_64 (default) selected with seed 861023459.
--<>--<>--<>--<>--<>--<>--<>--
(Thu Dec  5 15:27:10 2019)(0.0161173 [s])[Default,Printers][Info]:
Running shell command: rm -f pyscannerbit_run_data/pso_scan/samples//results.hdf5
--<>--<>--<>--<>--<>--<>--<>--
(Thu Dec  5 15:27:10 2019)(0.0218247 [s])[Default,Core]:
Starting scan.
--<>--<>--<>--<>--<>--<>--<>--
(Thu Dec  5 15:27:10 2019)(0.0257852 [s])[Default,Printers][Info]:
Assigned printer ID '0' to output quantity with label 'LogLike'
--<>--<>--<>--<>--<>--<>--<>--
(Thu Dec  5 15:27:10 2019)(0.0258922 [s])[Default,Printers][Info]:
Assigned printer ID '1' to output quantity with label 'pointID'
--<>--<>--<>--<>--<>--<>--<>--
(Thu Dec  5 15:27:10 2019)(0.0259315 [s])[Default,Printers][Info]:
Assigned printer ID '2' to output quantity with label 'MPIrank'
--<>--<>--<>--<>--<>--<>--<>--
(Thu Dec  5 15:27:10 2019)(0.0283821 [s])[Default,Printers][Info]:
Assigned printer ID '3' to output quantity with label 'default::x'
--<>--<>--<>--<>--<>--<>--<>--
(Thu Dec  5 15:27:10 2019)(0.028515 [s])[Default,Printers][Info]:
Assigned printer ID '4' to output quantity with label 'default::z'
--<>--<>--<>--<>--<>--<>--<>--
(Thu Dec  5 15:27:10 2019)(0.0285744 [s])[Default,Printers][Info]:
Assigned printer ID '5' to output quantity with label 'default::y'
--<>--<>--<>--<>--<>--<>--<>--
(Thu Dec  5 15:27:10 2019)(0.0289797 [s])[Default,Printers][Info]:
Assigned printer ID '6' to output quantity with label 'unitCubeParameters'
--<>--<>--<>--<>--<>--<>--<>--
